### ISSUE TITLE
Run EvoPress

### ISSUE THREAD

**Issue by guanchenl** [IST-DASLab/EvoPress#1]
Great framework!

I have some questions for EvoPress

1. Is this a valid config to run EvoPress (pruning) properly?

```bash
#!/bin/bash
export CUDA_VISIBLE_DEVICES=0,1
export SSL_CERT_DIR='/etc/ssl/certs'
export REQUESTS_CA_BUNDLE='/etc/ssl/certs/ca-certificates.crt'
export HF_DATASETS_CACHE=/xxxx/datasets/zeroshot/
export HF_ALLOW_CODE=1


torchrun --nnodes=1 --nproc_per_node=2 prune.py \
    --model_name_or_path /xxx/meta-llama/Meta-Llama-3.1-8B \
    --prunable_modules '^(?!.*(?:embedding|emb|head)).+$' \
    --pre_block_modules model.embed_tokens model.rotary_emb \
    --block_modules model.layers \
    --calibration_data c4 \
    --calibration_sequence_length 4096 \
    --sparsity 0.7 \
    --block_size 128 \
    --rel_damp 1e-2 \
    --dtype auto \
    --seed 0 \
    --low_cpu_mem_usage \
    --attn_implementation sdpa \
    --cpu_offload_modules \
    --cpu_offload_activations \
    --verbose \
    --save_dir ./None \
    --weights_diff 1000000 \
    --num_levels 8
```

2. Can EvoPress find an ideal sparsity distribution when performing structured pruning (to prune attn-heads and ffn-neurons) ?

3. Should I prune first or otherwise (evo)search the config first?

Best.

**Comment by guanchenl** [comment]
<img width="654" alt="image" src="https://github.com/user-attachments/assets/c218db46-a4e6-4cdb-84c3-365dfb88bf8a">

Another Question: Is the true pruning after a layer of optimization is dropped, and how can this ensure that errors are effectively accumulated?

**Comment by Godofnothing** [comment]
Hi, @guanchenl. 
Thanks for your interest in the project!

1. I would suggest specifying only projections inside attetnion blocks: `q_proj`, `k_proj`, e.t.c. RMSNorms are not expected to be pruned. In addition, one has to specify the directory to save sparse weights. Otherwise looks fine.
2. At the moment we support only pruning entire attention/ffn blocks. Attention head pruning and neuron pruning is not implemented yet.
3. You have to prune first, otherwise you have nothing to search over.

**Comment by Godofnothing** [comment]
@guanchenl concerning the second question - the referenced line corresponds to unstructured sparsity, not block pruning.

**Comment by guanchenl** [comment]
> 2. At the moment we support only pruning entire attention/ffn blocks. Attention head pruning and neuron pruning is not implemented yet.

I guess EvoPress' theory is fine in terms of supporting structured pruning? even though it's not currently implemented.

> concerning the second question - the referenced line corresponds to unstructured sparsity, not block pruning.

Sorry for misunderstanding, I mean in EvoPress, did you remove the “another forward propagation” feature adopted in SparseGPT to accumulate errors? That is:

<img width="678" alt="image" src="https://github.com/user-attachments/assets/ec1893f1-310a-4dbf-924e-35c803be491a">

Thanks for your response~

**Comment by Godofnothing** [comment]
@guanchenl 
1) EvoPress theory should be fine for structured sparsity. We hope to add this option later (but w/o strict timelines).
2) Since EvoPress produces multiple sparsity levels, there is no natural way to account for error accumulation, since keeping all possible paths is prohibitevely expensive. A natural option would be to keep average sparsity level. In some experiments I tried w/ and w/o "forward propagation" feature and difference was not very pronounced,

**Comment by OliverSieberling** [comment]
@guanchenl I have added some scripts in the example_scripts folder for reference

**Comment by guanchenl** [comment]
> @guanchenl I have added some scripts in the example_scripts folder for reference

Appreciate it!
